version: 0.2
phases:
  install:
    runtime-versions:
        ruby: 2.5.0
  build:
    commands:
      - sam package --template-file template.yml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-79jccgrc7srx --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml