version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "samhello"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-79jccgrc7srx"
s3_prefix = "samhello"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
